global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "auth-micro"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["app:44049"]
